### ISSUE TITLE
sshnp has to run directly i.e. ./sshnp as it calls sshrv from the directory it is running in

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#148]
### Describe the bug

If sshnp is placed in a directory and run via a $PATH it works but does not find the sshrv binary

```
cconstab@tarial ~ % $(sshnp -f @xxxxxx -t @yyyyy -d host  -h @aaaaa -s id_ed25519.pub)
Unhandled exception:
ProcessException: No such file or directory
  Command: /Users/cconstab/sshrv x.x.x.x 41311
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401)
#1      Process.start (dart:io-patch/process_patch.dart:38)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:578)
#3      Process.run (dart:io-patch/process_patch.dart:49)
#4      main (file:///Users/cconstab/Documents/GitHub/@foundation/sshnoports/bin/sshnp.dart:362)
<asynchronous suspension>
cconstab@tarial ~ %
```

### Steps to reproduce

1. First put sshnp  release in you home directory i.e ~/sshnp
2. Then cd to ~/sshnp and run ./sshnp and everything works, also works fine if you specify the full directory ~/sshnp/sshnp
3. And then cd .. and run the same command assuming ~/sshnp is in your PATH
4. Top put it in the path use `export PATH="~/sshnp:$PATH"` or similar for your shell

### Expected behavior

No matter where sshnp is running from it should find itself and the sshrv binary! 

Bug probably due to fact that dart has no idea of the PATH so need to find a way !

### Smartphones

- Linux
- v3.1.2 sshnp

### Were you using an atApplication when the bug was found?

sshnp

**Comment by cconstab** [comment]
work around for now is to cd to the ~/sshnp directory and run as ./sshnp

**Comment by cconstab** [comment]
This bug has re apeared with a new error (tests :-) )

```
Exception: sshnp is expected to be run as a compiled executable, not via the dart command
#0      SSHNP.getSshrvCommand (package:sshnoports/sshnp.dart:672)
#1      SSHNP.getHostAndPortFromSshrvd (package:sshnoports/sshnp.dart:423)
<asynchronous suspension>
#2      SSHNP.init (package:sshnoports/sshnp.dart:202)
<asynchronous suspension>
#3      main (file:///Users/cconstab/Documents/GitHub/@foundation/sshnoports/bin/sshnp.dart:21)
<asynchronous suspension>
cconstab@tarial ~ %
```


Needs fixing before next release

**Comment by gkc** [comment]
Arguably not a bug ... 
And definitely not this bug, I think :-)

Can you say what you were doing, Colin? I get this error in only two scenarios: (1) I am running via the dart command (2) I am running where the executable is sshnp.exe, not sshnp

For (1) I think this is currently working as intended. If we do want to run via the dart command, we can extend existing code to detect that it was run via the dart command, in which case it should build the sshrv command as a dart command as well, using a combination of Directory.current and Platform.executableArguments to find the expected location of the bin/sshrv.dart file

For (2) I think this is currently working as intended but we could perhaps be a bit more generous and instead of asserting that the resolved executable name is sshnp we could instead assert that the resolved executable name is not `dart`, or maybe that it starts with sshnp rather than being == sshnp

**Comment by cconstab** [comment]
I get the error when sshnp is run via PATH and cannot find sshrv.

 When run as an exe i.e after being compiled . Which was the original issue

**Comment by gkc** [comment]
ah I see - ty

**Comment by gkc** [comment]
Pull request with fix https://github.com/atsign-foundation/sshnoports/pull/215
