### ISSUE TITLE
NPT_Flutter shows disconnected but it is not

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#1572]
### Describe the bug

Connected to remote webserver which continued to be connected but the GUI said disconnected

### Steps to reproduce

1.Unknown

### Expected behavior

Display the actuall connectivity status ? 

### Screenshots

See attached video

https://github.com/user-attachments/assets/9b106141-1d0b-472b-89e9-0262703c7890

**Comment by xavierchanth** [comment]
I tested this quite thoroughly when I implemented, and I can see that the SocketConnector close is called in the app logs. My assumption is that the changes to socket connector are making the connection wait for the server side to close. Since we aren’t killing a process like we do for the binaries, it’s only affecting the app using latest socket connector. Will investigate to confirm.

**Comment by cconstab** [comment]
Do we by default use the -K keep alive as I do not see that as an option.. I have tested again and it is repeatable

**Comment by xavierchanth** [comment]
It works a little differently, it didn't make sense to offer it. The built-in settings are pretty much identical to what -K does.

**Comment by xavierchanth** [comment]
It will not restart the connection on failure though
