### ISSUE TITLE
SSHNP Automated e2e tests

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/noports#166]
### Is your feature request related to a problem? Please describe.

We do not currently have any automated end to end tests, so all testing is manually intensive and time-consuming

### Describe the solution you'd like

A set of tests of the following scenarios
- With 'new' atSigns, full scenario, single sshnp client - establish ssh session via sshrv, verify all worked and cleaned up correctly
- With 'existing' atSigns, same scenario
- For both of the above scenarios, with multiple concurrent sshnp clients
- Compatibility testing for all of the above - i.e. sshnpd from previous releases vs sshnp from latest trunk, sshnpd from latest trunk vs sshnp from previous releases, etc

### Additional context

Things that might help:
- There are tests in at_server which create, activate and onboard new atSigns in the staging environment, run the at_server e2e test pack using those atSigns, and then delete those atSigns at the end
- There has been work done on dockerizing sshnpd, sshnp and sshrv

**Comment by JeremyTubongbanua** [comment]
Testing method:

1. sshnp release vs. sshnpd trunk
2. sshnp release vs. sshnpd release
3. sshnp trunk vs. sshnpd trunk
4. sshnp trunk vs. sshnpd release

**EDIT:** this comment is stale

**Comment by JeremyTubongbanua** [comment]
Later, we should consider spinning up some staging atSigns and atServers

**Comment by JeremyTubongbanua** [comment]
Some blockers I have (that I believe are optional but still want thoughts):

- Can't run our own sshrvd in the testing because only one sshrvd instance can exist under one atSign at a time. I tried to run a job to setup an sshrvd, but I don't know how to make it so that the job's docker container stays alive and moves onto the next set of jobs @cpswan 
- For test coverage, should we set up a github action under a weekly cron job to sanity check things like our rendezvous points: @rv_am, @rv_eu,.., checking trunk against trunk, release against release, trunk against release, etc,... ? @gkc
