### ISSUE TITLE
Send ACK notification from sshnpd to sshnp

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/noports#24]
**Is your feature request related to a problem? Please describe.**
If sshnpd is not running at the other end, sshnp does not know that that is the case, and completes apparently successfully

**Describe the solution you'd like**
I'd like sshnp to receive a notification from sshnpd that it has received the request and perhaps a second notification from sshnpd saying that it has acted on the request (and if it couldn't, why not)

**Comment by cconstab** [comment]
Wonderful request.. Let me noodle and work on that for you..

**Comment by cconstab** [comment]
This issue is very much apparent when the link between servers is slow or has limited bandwith. Currently some commands are sent blindly with a timeout of 3 seconds and they can fail just because of the time taken.  Having an Ack can expand the timeout time and also finish interactions quickly once the Ack is received. 
Bumping to Urgent as this is important for low bandwidth / Cellular IoT connectivity.

Making new branch ack-notification if people want to track progress..

https://github.com/atsign-foundation/sshnoports/tree/ack-notification
