### ISSUE TITLE
refactor lib/sshnp.dart to allow it to be used in a desktop app as well as a CLI

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/noports#248]
### Is your feature request related to a problem? Please describe.

Currently there are some behaviours which will not work in a desktop app. For example exit statements

### Describe the solution you'd like

SSHNP class should be reusable in either the existing CLI or in the (new) desktop app.

**Comment by xavierchanth** [comment]
I will start this in tandem with the changes I'm doing for #196

**Comment by xavierchanth** [comment]
@gkc I noticed that the sessionId was not being used to generate the path in sshnpd...
https://github.com/atsign-foundation/sshnoports/blob/284b01cb14012a593d39b2a37edfd960fed48708/packages/sshnoports/lib/sshnpd.dart#L296-L314

but it is used in sshnp...

https://github.com/atsign-foundation/sshnoports/blob/284b01cb14012a593d39b2a37edfd960fed48708/packages/sshnoports/lib/sshnp.dart#L600-L618

I am trying to merge these two functions into a single one, since they are similar enough.
Should sshnpd's path also be '$atsign/$sessionId' for its hive path or should I make sessionId an optional part of the path like in my code below:

```dart
Future<AtClient> createAtClientCli(
    {required String homeDirectory,
    required String atsign,
    String? sessionId,                    // ! OPTIONAL
    required String atKeysFilePath}) async {
  
  String pathBase = '$homeDirectory/.sshnp/$atsign/';
  if (sessionId != null) {
    pathBase += '$sessionId/';            // ! ONLY ADDED WHEN NOT NULL
  }
  // ... rest of code
}
```

**Comment by xavierchanth** [comment]
Starting my work here:

I separated the Impl of SSHNPD to SSHNPDImpl

https://github.com/atsign-foundation/sshnoports/tree/xc-sshnp-refactor

There are technically breaking changes... but only to anyone depending on sshnoports as a library... I don't think we should let that stop us from making these improvements though. Especially since the binaries themselves will be non-breaking

**Comment by gkc** [comment]
@XavierChanth they are different for sshnpd vs sshnp because the storage path acts as a kind of a mutex. We want only one sshnpd to be running at any given time for a given user on a given host or container; but we want to allow many sshnp to be run concurrently

@cconstab can explain further

FYI I'm out of office until Monday now so I'll be catching up with work stuff once or twice a day Thu & Fri but not at all on Sat & Sun

**Comment by xavierchanth** [comment]
Closed by the latest refactoring
