### ISSUE TITLE
trunk sshnp.dart throws runtime errors like `type 'String' is not a subtype of type 'int?'` for `-P` option

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#421]
### Describe the bug

When running -P, error reported..

```
cconstab@tarial sshnoports % dart run bin/sshnp.dart 
Version : 4.0.0-rc.2
-k, --key-file              Sending atSign's atKeys file if not in ~/.atsign/keys/
-f, --from (mandatory)      Sending (a.k.a. client) atSign
-t, --to (mandatory)        Receiving device atSign
-d, --device                Receiving device name
                            (defaults to "default")
-h, --host (mandatory)      atSign of sshrvd daemon or FQDN/IP address to connect back to
-p, --port                  TCP port to connect back to (only required if --host specified a FQDN/IP)
                            (defaults to "22")
-l, --local-port            Reverse ssh port to listen on, on your local machine, by sshnp default finds a spare port
                            (defaults to "0")
-s, --ssh-public-key        Public key file from ~/.ssh to be appended to authorized_hosts on the remote device
                            (defaults to "")
-o, --local-ssh-options     Add these commands to the local ssh command
-v, --[no-]verbose          More logging
-r, --[no-]rsa              Use RSA 4096 keys rather than the default ED25519 keys
-u, --remote-user-name      username to use in the ssh session on the remote host
    --root-domain           atDirectory domain
                            (defaults to "root.atsign.org")
-P, --local-sshd-port       port sshd is listening locally on localhost
                            (defaults to "22")
    --[no-]legacy-daemon    Request is to a legacy (< 3.5.0) noports daemon
                            (defaults to on)
    --config-file           Read args from a config file
                            Mandatory args are not required if already supplied in the config file
    --list-devices          List available devices

Invalid argument(s): Option from is mandatory.
cconstab@tarial sshnoports % dart run bin/sshnp.dart -f @cconstab -t @ssh_1 -h @rv_am -d cally -P 22
```

### Steps to reproduce

1. Run above commandor similar and it errors out

### Expected behavior

No error and -P option works as it did in 3.4.x

### Smartphones

- Device Linux/Mac

**Comment by cconstab** [comment]
Not had time to figure out where the erro is as yet but wanted to make not of it and get a test in place, which I think @JeremyTubongbanua had been looking into..

**Comment by JeremyTubongbanua** [comment]
> Not had time to figure out where the erro is as yet but wanted to make not of it and get a test in place, which I think @JeremyTubongbanua had been looking into..

Yes, there's a ticket which I believe is #375 , I will see if I can get it into this sprint

**Comment by xavierchanth** [comment]
@cconstab It's unclear what's wrong, can you explain what the problem is and why it's a problem

**Comment by xavierchanth** [comment]
P.S. I think some of your logs are missing

**Comment by cconstab** [comment]
Try adding -P to  sshnp

It fails

String is not an int?

**Comment by gkc** [comment]
I think 4.0.0-rc2 predates the addition of the -P option.

**Comment by gkc** [comment]
But 4.0.0-rc2 definitely isn't latest version; it was built three weeks ago to support pen testing

**Comment by cconstab** [comment]
I was building from trunk

**Comment by gkc** [comment]
> I was building from trunk

Ah OK. I'll correct the title of the ticket

@XavierChanth The issue here is when `factory SSHNPPartialParams.fromArgMap` calls the `SSHNPPartialParams` constructor
```
  factory SSHNPPartialParams.fromArgMap(Map<String, dynamic> args) {
    return SSHNPPartialParams(
      profileName: args['profile-name'],
      clientAtSign: args['from'],
      sshnpdAtSign: args['to'],
      host: args['host'],
      device: args['device'],
      port: args['port'],
      localPort: args['local-port'],
      atKeysFilePath: args['key-file'],
      sendSshPublicKey: args['ssh-public-key'],
      localSshOptions: args['local-ssh-options'] ?? SSHNP.defaultLocalSshOptions,
      rsa: args['rsa'],
      remoteUsername: args['remote-user-name'],
      verbose: args['verbose'],
      rootDomain: args['root-domain'],
      localSshdPort: args['local-sshd-port'],
      listDevices: args['list-devices'] ?? SSHNP.defaultListDevices,
      legacyDaemon: args['legacy-daemon'],
    );
  }
```
`args['port']`, `args['local-port']` and `args['local-sshd-port']` will all be Strings (or null if not supplied or defaulted) whereas the SSHNPPartialParams constructor expects `int?`

I'm not overly familiar with the new args parsing code but a couple of options spring to mind
1. modify the code above so it calls int.parse on those values if they are Strings rather than int or null - this is simple and will work fine but is a little ugly
2. modify this line in `SSHNPPartialParams.fromArgs` : `Map<String, dynamic> parsedArgsMap = {for (var e in (parsedArgs.options)) e: parsedArgs[e]};` so that instead it does something similar to `_parseConfigFile` and populates the arg map with values of the appropriate type. This is cleaner but is a little more work.

Any other options spring to mind?

**Comment by xavierchanth** [comment]
I created a solution in #427 which uses proposal 2:

> 2\. modify this line in `SSHNPPartialParams.fromArgs` : `Map<String, dynamic> parsedArgsMap = {for (var e in (parsedArgs.options)) e: parsedArgs[e]};` so that instead it does something similar to `_parseConfigFile` and populates the arg map with values of the appropriate type. This is cleaner but is a little more work.

That annoying line to cast ArgResults to Map<String, dynamic> drives me up the wall... but since it must be there might as well leverage that, since the argMap should never contain String port numbers in the first place, we should cast them as soon as possible.

Mini rant: Why must args make it so that ArgResults does not implement Map<String, dynamic>, nor exposes the internal Map<String, dynamic> options, nor is it possible to extend ArgResults either (because the only public constructors are factories). We must literally duplicate memory just to use it...

The maintainer's reply to my note added to the issue that's been open for 8 years :) 
<img width="562" alt="CleanShot 2023-09-07 at 10 17 06@2x" src="https://github.com/atsign-foundation/sshnoports/assets/33691921/45cb496b-2c8c-4b10-8077-3c1e27341d25">
