### ISSUE TITLE
Better fonts in the SSH No Ports GUI

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#821]
### Is your feature request related to a problem? Please describe.

The font is super small and not resizable/selectable

### Describe the solution you'd like

One or a choice of these fonts

https://www.nerdfonts.com/#home

### Describe alternatives you've considered

just a resize button -+

**Comment by xavierchanth** [comment]
It seems there aren't many resources on using system native fonts in flutter. The best short term solution would be to include a bunch as assets to pick from.

**Comment by cconstab** [comment]
Yup thats the onlybway I have done it

**Comment by CurtlyCritchlow** [comment]
@XavierChanth and @cconstab  Tried using a few nerd fonts, The terminal looks better but the it didn't fix the border problem.

<img width="800" alt="image" src="https://github.com/atsign-foundation/noports/assets/44856451/f8f4f612-3ce7-46b8-8cb7-6f1d4506268d">

Might be an encoding [issue](https://superuser.com/questions/735269/why-does-yast-now-show-lines-as-lqqqqqqqqqqqqqqq)

**Comment by xavierchanth** [comment]
What happens if you try typing emojis / other unicode characters into the terminal? That should tell us if it is an encoding related issue in the Flutter library itself.

It could also be the configuration of the system, we would need @JeremyTubongbanua to test that application as that unix user to see if there are any issues. For all we know Jeremy might also get qqqqqq instead of the unicode divider characters.

Also have you confirmed that this is in-fact the nerd font, are you able to paste nerd font characters in? For example, from macos font book:

![CleanShot 2024-02-28 at 12 16 32@2x](https://github.com/atsign-foundation/noports/assets/33691921/67db907b-eff0-411a-86a8-a5d07b446491)

**Comment by CurtlyCritchlow** [comment]
@XavierChanth, yes I'm passing nerd front to the terminal in the desktop app. ```[log] TextStyle(inherit: true, family: IosevkaTermNerdFontPropo)```

**Comment by CurtlyCritchlow** [comment]
Closing this ticket, fix has been merged into no_ports_desktop_1.0.0+5
